POST http://localhost:5500/api/poems
Content-Type: application/json

{
  "title": "I",
  "content": [
    {
      "line": "The art of losing isn’t hard to master",
      "author": "Elizabeth Bishop"
    }
  ],
  "archived": false
}



